env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'standard'
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'next/core-web-vitals'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'react'
  - '@typescript-eslint'
rules:
  react/display-name: 0
  react/react-in-jsx-scope: 0
settings:
  react:
    version: 'detect'
